var RED = '#E75C3C',
    ORANGE = '#E67E22',
    PURPLE = '#9B59B6',
    BLUE = '#2980B9',
    PINK = '#E91E63',
    YELLOW = '#F1C40F',
    GOLD = '#F39C12'
    GREEN = '#2ECC71',
    GREY = '#7F8C8D',
    SILVER = '#BDC3C7'
    WHITE = '#ECF0F1',
    BLACK = '#000000',
    BROWN = '#795548';

var western = {
    'Anger': RED,
    'Authority': BLACK,
    'Beauty': PURPLE,
    'Children': PINK,
    'Cold': BLUE,
    'Courage': ORANGE,
    'Cowardice': YELLOW,
    'Cruelty': PURPLE,
    'Danger': RED,
    'Death': BLACK,
    'Decadence': PURPLE,
    'Desire': RED,
    'Earthy': BROWN,
    'Energy': YELLOW,
    'Erotic': ORANGE,
    'Femininity': PINK,
    'Flamboyance': PURPLE,
    'Freedom': BLUE,
    'Friendly': ORANGE,
    'Fun': YELLOW,
    'Good Luck': GREEN,
    'Growth': GREEN,
    'Happiness': YELLOW,
    'Healing': BLUE,
    'Heat': RED,
    'Heaven': WHITE,
    'Intelligence': BLUE,
    'Jealousy': GREEN,
    'Love': RED,
    'Loyalty': BLUE,
    'Luxury': WHITE,
    'Marriage': WHITE,
    'Modesty': PURPLE,
    'Money': GOLD,
    'Mourning': BLACK,
    'Mystery': PURPLE,
    'Nature': GREEN,
    'Passion': RED,
    'Peace': YELLOW,
    'Personal Power': PURPLE,
    'Purity': WHITE,
    'Radicalism': RED,
    'Rational': BLUE,
    'Reliable': BROWN,
    'Repels Evil': YELLOW,
    'Respect': GREY,
    'Style': BLACK,
    'Truce': WHITE,
    'Unhappiness': BLUE,
    'Virtue': PURPLE
};

var japanese = {
    'Art/Creativity': RED,
    'Bad Luck': BLACK,
    'Balance': ORANGE,
    'Celebration': PURPLE,
    'Children': PINK,
    'Cold': BLUE,
    'Courage': YELLOW,
    'Cowardice': YELLOW,
    'Danger': RED,
    'Death': BLACK,
    'Decadence': PURPLE,
    'Deceit': YELLOW,
    'Desire': RED,
    'Energy': ORANGE,
    'Erotic': PINK,
    'Eternity': GREEN,
    'Evil': BLACK,
    'Excitement': RED,
    'Flamboyance': ORANGE,
    'God': PURPLE,
    'Good Luck': GREEN,
    'Healthy': PINK,
    'Heaven': YELLOW,
    'Holiness': WHITE,
    'Ilness': YELLOW,
    'Insight': PURPLE,
    'Intelligence': SILVER,
    'Religion': YELLOW,
    'Jealousy': GREEN,
    'Joy': YELLOW,
    'Life': BLUE,
    'Love': RED,
    'Loyalty': BLUE,
    'Modesty': GREY,
    'Money': BLUE,
    'Mystery': PURPLE,
    'Nature': GREEN,
    'Passion': RED,
    'Peace': BLUE,
    'Purity': WHITE,
    'Rational': BLUE,
    'Reliable': GREY,
    'Repels Evil': RED,
    'Respect': WHITE,
    'Strength': RED,
    'Style': BLACK,
    'Truce': WHITE,
    'Unhappiness': BLACK,
    'Warmth': ORANGE,
    'Wisdom': PURPLE
};

var hindu = {
    'Anger': BLACK,
    'Art/Creativity': BLUE,
    'Compassion': GREEN,
    'Courage': ORANGE,
    'Death': WHITE,
    'Desire': ORANGE,
    'Energy': RED,
    'Erotic': RED,
    'Evil': BLACK,
    'Fun': YELLOW,
    'God': YELLOW,
    'Gods': BLUE,
    'Happiness': GREEN,
    'Heat': RED,
    'Illness': YELLOW,
    'Insight': GREEN,
    'Intelligence': WHITE,
    'Intuition': PURPLE,
    'Religion': GREEN,
    'Joy': YELLOW,
    'Life': GREEN,
    'Love': GREEN,
    'Marriage': RED,
    'Passion': RED,
    'Peace': WHITE,
    'Penance': BLACK,
    'Personal Power': YELLOW,
    'Repels Evil': YELLOW,
    'Truce': WHITE,
    'Wisdom': PURPLE
};

var native_american = {
    'Balance': BLACK,
    'Cold': BLUE,
    'Danger': YELLOW,
    'Death': BLACK,
    'Friendly': GREY,
    'Gratitude': PURPLE,
    'Happiness': WHITE,
    'Healing': ORANGE,
    'Insight': YELLOW,
    'Intuition': BLUE,
    'Learning': ORANGE,
    'Love': YELLOW,
    'Passion': RED,
    'Peace': WHITE,
    'Personal Power': GREEN,
    'Respect': SILVER,
    'Self-Cultivation': BLACK,
    'Success': RED,
    'Trouble': BLUE,
    'Unhappiness': BLUE,
    'Wisdom': BROWN
};

var chinese = {
    'Celebration': BLACK,
    'Death': WHITE,
    'Earthy': BROWN,
    'Family': ORANGE,
    'Fertility': RED,
    'Good Luck': RED,
    'Growth': GREEN,
    'Happiness': RED,
    'Healthy': YELLOW,
    'Learning': ORANGE,
    'Life': GREEN,
    'Marriage': RED,
    'Mourning': WHITE,
    'Repels Evil': GREEN,
    'Respect': YELLOW,
    'Royalty': YELLOW,
    'Success': RED,
    'Money': GOLD,
    'Purity': WHITE,
    'Truce': WHITE,
};

var asian = {
    'Balance': GREEN,
    'Children': WHITE,
    'Eternity': GREEN,
    'Evil': BLACK,
    'Excitement': GREEN,
    'Flamboyance': PURPLE,
    'Happiness': RED,
    'Holiness': YELLOW,
    'Intelligence': BLACK,
    'Money': GOLD,
    'Penance': BLACK,
    'Power': YELLOW,
    'Purity': WHITE,
    'Repels Evil': YELLOW,
    'Self Cultivation': BLACK,
    'Strength': YELLOW,
    'Success': RED
};

var eastern_european = {
    'Anger': RED,
    'Heat': RED,
    'Beauty': RED,
    'Good Luck': RED,
    'Heat': RED,
    'Love': RED,
    'Loyalty': BLUE,
    'Mourning': YELLOW,
    'Passion': RED,
    'Power': RED,
    'Radicalism': RED,
    'Truce': WHITE,
    'Trust': WHITE,
    'Virtue': BLUE,
    'Wisdom': BLUE
};

var muslim = {
    'Death': SILVER,
    'God': GREEN,
    'Good Luck': GREEN,
    'Heat': RED,
    'Heaven': GREEN,
    'Religion': GREEN,
    'Peace': SILVER,
    'Purity': SILVER,
    'Strength': YELLOW,
    'Truce': SILVER
};

var african = {
    'Anger': RED,
    'Good Luck': RED,
    'Religion': GREEN,
    'Learning': GREEN,
    'Life': BLUE,
    'Peace': BLUE,
    'Success': GREEN,
    'Truce': GREY
};

var south_american = {
    'Danger': RED,
    'Death': GREEN,
    'Mourning': PURPLE,
    'Success': RED,
    'Trouble': BLUE
};
